version: '3.8'
services:
  elasticsearch:
    container_name: clip_elasticsearch
    build: ./elasticsearch
    ports:
      - "9200:9200"
    networks:
      - clip_multimodal
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme
      - TZ=Asia/Seoul
  kibana:
    container_name: clip_kibana
    build: ./kibana
    ports:
      - "5601:5601"
    networks:
      - clip_multimodal
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

networks:
  clip_multimodal:
    external: true